const listData = [
    {
    id : 1,
    amenities: "Furnished",
    image: "Img1.jpg",
    price: "Rp.9.000.000",
    rent: "Year",
    property: {
        beds: "3",
        Bats: "2",
        Area: "1800 ft",
      },
    addres: "Tangerang Selatan, Pondok Aren",
    },
    {
    id : 2,
    amenities: "Furnished",
    image: "Img2.jpg",
    price: "Rp.3.000.000",
    rent: "Year",
    property: {
        beds: "3",
        Bats: "2",
        Area: "1800 ft",
      },
    addres: "Tangerang Selatan, Pondok Aren",
    },
    {
    id : 3,
    amenities: "Furnished",
    image: "Img3.jpg",
    price: "Rp.5.000.000",
    rent: "Year",
    property: {
    beds: "3",
    Bats: "2",
    Area: "1800 ft",
    },
    addres: "Tangerang Selatan, Pondok Aren",
    },
    {
    id : 4,
    amenities: "Furnished",
    image: "Img4.jpg",
    price: "Rp.13.000.000",
    rent: "Year",
    property: {
    beds: "3",
    Bats: "2",
    Area: "1800 ft",
    },    
    addres: "Tangerang Selatan, Pondok Aren",
    },
    {
    id : 5,
    amenities: "Furnished",
    image: "Img5.jpg",
    price: "Rp.3.500.000",
    rent: "Year",
    property: {
    beds: "3",
    Bats: "2",
    Area: "1800 ft",
    },
    addres: "Tangerang Selatan, Pondok Aren",
    },
    {
    id : 6,
    amenities: "Furnished",
    image: "Img6.jpg",
    price: "Rp.5.500.000",
    rent: "Year",
    property: {
    beds: "3",
    Bats: "2",
    Area: "1800 ft",
    },addres: "Tangerang Selatan, Pondok Aren",
    },
    {
    id : 7,
    amenities: "Furnished",
    image: "Img7.jpg",
    price: "Rp.13.000.000",
    rent: "Year",
    property: {
    beds: "3",
    Bats: "2",
    Area: "1800 ft",
     },
    addres: "Tangerang Selatan, Pondok Aren",
    },
    {
    id : 8,
    amenities: "Furnished",
    image: "Img8.jpg",
    price: "Rp.3.500.000",
    rent: "Year",
    property: {
    beds: "3",
    Bats: "2",
    Area: "1800 ft",
    },
    addres: "Tangerang Selatan, Pondok Aren",
    },
    {
    id : 9,
    amenities: "Furnished",
    image: "Img9.jpg",
    price: "Rp.5.500.000",
    rent: "Year",
    property: {
    beds: "3",
    Bats: "2",
    Area: "1800 ft",
    },
    // property: "2 Beds, 2 Bats, 1,900 sqft",
    addres: "Tangerang Selatan, Pondok Aren",
    },
]

export default listData;